{
    'name': 'Oacis Grievance',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Grievance Management',
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://www.precisefect.com',
    'license': 'OPL-1',
    'depends': ['oacis_student', 'oacis_faculty_profile', 'oacis_guardian', 'oacis_notify', 'oacis_portal_student', 'oacis_portal_guardian'],
    'data': [
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'views/grievance_views.xml',
        'views/menu.xml',
        'views/portal_templates.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
