{
    'name': 'Grading & Results',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Marks entry, grade computation, GPA/CGPA and semester results',
    'description': """
        Marks entry, grade computation, GPA/CGPA and semester results
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'unicore_academic',
        'unicore_attendance',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_enrollment',
        'unicore_exam',
        'unicore_faculty_profile',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_grading_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_grade_scale_data.xml',
        'data/unicore_transcript_report_action.xml',
        'views/unicore_grade_scale_views.xml',
        'views/unicore_grade_entry_views.xml',
        'views/unicore_semester_result_views.xml',
        'views/grading_search_list_phase1.xml',
        'views/unicore_student_result_views.xml',
        'views/unicore_transcript_template.xml',
        'views/unicore_grading_kanban_views.xml',
        'views/unicore_grading_calendar_views.xml',
        'views/unicore_grading_analysis_views.xml',
        'views/unicore_grading_activity_views.xml',
        'menus/unicore_grading_menus.xml',
        'views/unicore_grading_view_mode_ext.xml',
        'views/unicore_grading_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_grading,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
