{
    'name': 'Timetable & Scheduling',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Class scheduling, time slots and conflict-free timetable generation',
    'description': """
        Class scheduling, time slots and conflict-free timetable generation
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'unicore_academic',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_faculty_profile',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
    ],
    'data': [
        'security/unicore_timetable_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_time_slot_demo_data.xml',
        'views/unicore_time_slot_views.xml',
        'views/unicore_timetable_entry_views.xml',
        'views/timetable_search_calendar_phase1.xml',
        'views/unicore_room_booking_views.xml',
        'views/unicore_timetable_kanban_views.xml',
        'views/unicore_timetable_calendar_views.xml',
        'menus/unicore_timetable_menus.xml',
        'views/unicore_timetable_view_mode_ext.xml',
        'views/unicore_timetable_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_timetable,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
