{
    'name': 'Fees',
    'version': '19.0.1.1.0',
    'category': 'Education',
    'summary': 'Student fee management, invoicing and payment tracking',
    'description': """
        Student fee management, invoicing and payment tracking
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'account',
        'mail',
        'unicore_academic',
        'unicore_attendance',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_admission',
        'unicore_exam',
        'unicore_faculty_profile',
        'unicore_grading',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_fees_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_fees_sequence_data.xml',
        'data/unicore_fees_cron_data.xml',
        'views/unicore_student_partner_ext_views.xml',
        'views/unicore_fee_structure_views.xml',
        'views/unicore_fee_invoice_views.xml',
        'views/unicore_fee_invoice_gl_ext_views.xml',
        'views/unicore_student_fee_ext_views.xml',
        'views/unicore_fee_receipt_template.xml',
        'data/unicore_fee_receipt_report_action.xml',
        'views/unicore_fee_accounting_config_views.xml',
        'views/unicore_fee_batch_wizard_views.xml',
        'views/fee_invoice_search_phase1.xml',
        'views/unicore_fees_kanban_views.xml',
        'views/unicore_fees_calendar_views.xml',
        'views/unicore_fees_activity_views.xml',
        'menus/unicore_fees_menus.xml',
        'views/unicore_fees_view_mode_ext.xml',
        'views/unicore_fees_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_fees,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
