{
    'name': 'Fees',
    'version': '19.0.1.1.0',
    'category': 'Education',
    'summary': 'Student fee management, invoicing and payment tracking',
    'description': """
        Student fee management, invoicing and payment tracking
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'account',
        'mail',
        'oacis_academic',
        'oacis_attendance',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_exam',
        'oacis_faculty_profile',
        'oacis_grading',
        'oacis_guardian',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_fees_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_fees_sequence_data.xml',
        'data/oacis_fees_cron_data.xml',
        'views/oacis_student_partner_ext_views.xml',
        'views/oacis_fee_structure_views.xml',
        'views/oacis_fee_invoice_views.xml',
        'views/oacis_fee_invoice_gl_ext_views.xml',
        'views/oacis_student_fee_ext_views.xml',
        'views/oacis_fee_receipt_template.xml',
        'data/oacis_fee_receipt_report_action.xml',
        'views/oacis_fee_accounting_config_views.xml',
        'views/oacis_fee_batch_wizard_views.xml',
        'views/fee_invoice_search_phase1.xml',
        'views/oacis_fees_kanban_views.xml',
        'views/oacis_fees_calendar_views.xml',
        'views/oacis_fees_activity_views.xml',
        'menus/oacis_fees_menus.xml',
        'views/oacis_fees_view_mode_ext.xml',
        'views/oacis_fees_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_fees,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
