{
    'name': 'Hostel',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'University hostel and accommodation management for student residences',
    'description': """
        University hostel and accommodation management for student residences
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'oacis_academic',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_security',
        'oacis_student',
    ],
    'data': [
        'security/oacis_hostel_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_hostel_sequence_data.xml',
        'views/oacis_hostel_block_views.xml',
        'views/oacis_hostel_room_views.xml',
        'views/oacis_hostel_allocation_views.xml',
        'views/oacis_hostel_maintenance_views.xml',
        'views/hostel_search_phase1.xml',
        'views/oacis_hostel_kanban_views.xml',
        'views/oacis_hostel_calendar_views.xml',
        'views/oacis_hostel_analysis_views.xml',
        'views/oacis_hostel_activity_views.xml',
        'menus/oacis_hostel_menus.xml',
        'views/oacis_hostel_view_mode_ext.xml',
        'views/oacis_hostel_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_hostel,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
