{
    'name': 'Transport',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'University student transport management with routes and passes',
    'description': """
        University student transport management with routes and passes
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'unicore_academic',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_security',
        'unicore_student',
    ],
    'data': [
        'security/unicore_transport_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_transport_sequence_data.xml',
        'views/unicore_transport_vehicle_views.xml',
        'views/unicore_transport_route_views.xml',
        'views/unicore_transport_pass_views.xml',
        'views/unicore_transport_trip_views.xml',
        'views/transport_search_phase1.xml',
        'views/unicore_transport_kanban_views.xml',
        'views/unicore_transport_calendar_views.xml',
        'menus/unicore_transport_menus.xml',
        'views/unicore_transport_view_mode_ext.xml',
        'views/unicore_transport_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_transport,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
