{
    'name': 'Scholarships',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Scholarship programs, applications and financial aid disbursement',
    'description': """
        Scholarship programs, applications and financial aid disbursement
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'oacis_academic',
        'oacis_attendance',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_exam',
        'oacis_faculty_profile',
        'oacis_fees',
        'oacis_grading',
        'oacis_guardian',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_scholarship_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_scholarship_sequence_data.xml',
        'views/oacis_scholarship_award_views.xml',
        'views/oacis_scholarship_application_views.xml',
        'views/oacis_scholarship_program_views.xml',
        'views/scholarship_search_list_phase1.xml',
        'views/oacis_student_scholarship_ext_views.xml',
        'views/oacis_scholarship_kanban_views.xml',
        'views/oacis_scholarship_calendar_views.xml',
        'views/oacis_scholarship_analysis_views.xml',
        'views/oacis_scholarship_activity_views.xml',
        'menus/oacis_scholarship_menus.xml',
        'views/oacis_scholarship_view_mode_ext.xml',
        'views/oacis_scholarship_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_scholarship,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
