{
    'name': 'Scholarships',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Scholarship programs, applications and financial aid disbursement',
    'description': """
        Scholarship programs, applications and financial aid disbursement
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'unicore_academic',
        'unicore_attendance',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_admission',
        'unicore_exam',
        'unicore_faculty_profile',
        'unicore_fees',
        'unicore_grading',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_scholarship_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_scholarship_sequence_data.xml',
        'views/unicore_scholarship_award_views.xml',
        'views/unicore_scholarship_application_views.xml',
        'views/unicore_scholarship_program_views.xml',
        'views/scholarship_search_list_phase1.xml',
        'views/unicore_student_scholarship_ext_views.xml',
        'views/unicore_scholarship_kanban_views.xml',
        'views/unicore_scholarship_calendar_views.xml',
        'views/unicore_scholarship_analysis_views.xml',
        'views/unicore_scholarship_activity_views.xml',
        'menus/unicore_scholarship_menus.xml',
        'views/unicore_scholarship_view_mode_ext.xml',
        'views/unicore_scholarship_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_scholarship,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
