{
    'name': 'Examination Management',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Exam scheduling, hall tickets, seating plans and eligibility checks',
    'description': """
        Exam scheduling, hall tickets, seating plans and eligibility checks
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'oacis_academic',
        'oacis_attendance',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_faculty_profile',
        'oacis_guardian',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_exam_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_exam_sequence_data.xml',
        'views/oacis_exam_hall_ticket_views.xml',
        'views/oacis_exam_seating_views.xml',
        'views/oacis_exam_schedule_views.xml',
        'views/exam_search_phase1.xml',
        'views/oacis_hall_ticket_template.xml',
        'data/oacis_hall_ticket_report_action.xml',
        'views/oacis_exam_kanban_views.xml',
        'views/oacis_exam_calendar_views.xml',
        'views/oacis_exam_activity_views.xml',
        'menus/oacis_exam_menus.xml',
        'views/oacis_exam_view_mode_ext.xml',
        'views/oacis_exam_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_exam,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
