{
    'name': 'Examination Management',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Exam scheduling, hall tickets, seating plans and eligibility checks',
    'description': """
        Exam scheduling, hall tickets, seating plans and eligibility checks
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'unicore_academic',
        'unicore_attendance',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_enrollment',
        'unicore_faculty_profile',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_exam_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_exam_sequence_data.xml',
        'views/unicore_exam_hall_ticket_views.xml',
        'views/unicore_exam_seating_views.xml',
        'views/unicore_exam_schedule_views.xml',
        'views/exam_search_phase1.xml',
        'views/unicore_hall_ticket_template.xml',
        'data/unicore_hall_ticket_report_action.xml',
        'views/unicore_exam_kanban_views.xml',
        'views/unicore_exam_calendar_views.xml',
        'views/unicore_exam_activity_views.xml',
        'menus/unicore_exam_menus.xml',
        'views/unicore_exam_view_mode_ext.xml',
        'views/unicore_exam_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_exam,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
