{
    'name': 'Timetable & Scheduling',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Class scheduling, time slots and conflict-free timetable generation',
    'description': """
        Class scheduling, time slots and conflict-free timetable generation
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'oacis_academic',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_faculty_profile',
        'oacis_guardian',
        'oacis_security',
        'oacis_student',
    ],
    'data': [
        'security/oacis_timetable_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_time_slot_demo_data.xml',
        'views/oacis_time_slot_views.xml',
        'views/oacis_timetable_entry_views.xml',
        'views/timetable_search_calendar_phase1.xml',
        'views/oacis_room_booking_views.xml',
        'views/oacis_timetable_kanban_views.xml',
        'views/oacis_timetable_calendar_views.xml',
        'menus/oacis_timetable_menus.xml',
        'views/oacis_timetable_view_mode_ext.xml',
        'views/oacis_timetable_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_timetable,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
