{
    'name': 'UniCore Faculty & Staff',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Faculty member and administrative staff profile management',
    'description': """
        Faculty member and administrative staff profile management
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'unicore_academic',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_security',
        'unicore_student',
    ],
    'data': [
        'security/unicore_faculty_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_faculty_sequence_data.xml',
        'views/unicore_faculty_qualification_views.xml',
        'views/unicore_faculty_publication_views.xml',
        'views/unicore_faculty_workload_views.xml',
        'views/unicore_staff_member_views.xml',
        'views/unicore_faculty_member_views.xml',
        'views/unicore_faculty_profile_kanban_views.xml',
        'menus/unicore_faculty_profile_menus.xml',
        'views/unicore_faculty_profile_view_mode_ext.xml',
        'views/unicore_faculty_profile_cleanup.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
