{
    'name': 'Library',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'University library management with catalogue, issue tracking and fines',
    'description': """
        University library management with catalogue, issue tracking and fines
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'oacis_academic',
        'oacis_base',
        'oacis_campus',
        'oacis_faculty_profile',
        'oacis_security',
        'oacis_student',
    ],
    'data': [
        'security/oacis_library_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_library_config_data.xml',
        'views/oacis_library_book_views.xml',
        'views/oacis_library_member_views.xml',
        'views/oacis_library_issue_views.xml',
        'views/library_issue_search_phase1.xml',
        'views/oacis_library_reservation_views.xml',
        'views/oacis_library_kanban_views.xml',
        'views/oacis_library_calendar_views.xml',
        'views/oacis_library_analysis_views.xml',
        'views/oacis_library_activity_views.xml',
        'menus/oacis_library_menus.xml',
        'views/oacis_library_view_mode_ext.xml',
        'views/oacis_library_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_library,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
