{
    'name': 'Finance Reports',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Financial dashboards, fee analytics and revenue reporting',
    'description': """
        Financial dashboards, fee analytics and revenue reporting
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'oacis_academic',
        'oacis_attendance',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_exam',
        'oacis_faculty_profile',
        'oacis_fees',
        'oacis_grading',
        'oacis_guardian',
        'oacis_scholarship',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_finance_report_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_finance_report_cron.xml',
        'views/oacis_fee_invoice_report_views.xml',
        'views/oacis_fee_payment_report_views.xml',
        'views/oacis_finance_snapshot_views.xml',
        'views/oacis_finance_kpi_views.xml',
        'views/oacis_finance_dashboard_views.xml',
        'report/oacis_fee_statement_report.xml',
        'report/oacis_fee_statement_template.xml',
        'menus/oacis_finance_report_menus.xml',
        'views/oacis_finance_report_view_mode_ext.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_finance_report,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
