{
    'name': 'UniCore Student Enrollment',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Student course registration, waitlist management and add/drop processing',
    'description': """
        Student course registration, waitlist management and add/drop processing
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'unicore_academic',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_faculty_profile',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_enrollment_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_enrollment_sequence_data.xml',
        'views/unicore_enrollment_views.xml',
        'views/unicore_enrollment_waitlist_views.xml',
        'views/unicore_enrollment_log_views.xml',
        'views/unicore_course_offering_ext_views.xml',
        'views/unicore_student_ext_enrollment_views.xml',
        'views/unicore_enrollment_kanban_views.xml',
        'views/unicore_enrollment_calendar_views.xml',
        'views/unicore_enrollment_analysis_views.xml',
        'views/unicore_enrollment_activity_views.xml',
        'menus/unicore_enrollment_menus.xml',
        'views/unicore_enrollment_view_mode_ext.xml',
        'views/unicore_enrollment_cleanup.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
