"""
Oacis Finance Snapshot Model
Daily snapshot of key financial metrics for
trend analysis. Generated by a scheduled action
(cron job) once per day. Stores aggregate totals
so historical trends can be viewed without
computing from transactional data every time.
"""

import logging
from datetime import date

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class OacisFinanceSnapshot(models.Model):
    _name = 'oacis.finance.snapshot'
    _description = 'Daily Financial Snapshot'
    _rec_name = 'display_name'
    _inherit = ['oacis.mixin']

    display_name = fields.Char(
        string='Display Name',
        compute='_compute_display_name',
        store=True,
        depends=['academic_year_id.display_name', 'semester_id.display_name',
                 'snapshot_date'],
    )

    @api.depends('academic_year_id.display_name', 'semester_id.display_name',
                 'snapshot_date')
    def _compute_display_name(self):
        for rec in self:
            context = (
                rec.academic_year_id.display_name
                or rec.semester_id.display_name
                or ''
            )
            if rec.snapshot_date:
                rec.display_name = '%s - %s' % (
                    context,
                    rec.snapshot_date.strftime('%d %b %Y'),
                )
            else:
                rec.display_name = context
    _order = 'snapshot_date desc, company_id'
    _check_company_auto = True

    snapshot_date = fields.Date(
        string='Snapshot Date',
        required=True,
        index=True,
        default=fields.Date.today,
    )
    company_id = fields.Many2one(
        comodel_name='res.company',
        string='Institution',
        required=True,
        default=lambda self: self.env.company,
        ondelete='restrict',
        index=True,
    )
    academic_year_id = fields.Many2one(
        comodel_name='oacis.academic.year',
        string='Academic Year',
        ondelete='set null',
    )
    semester_id = fields.Many2one(
        comodel_name='oacis.semester',
        string='Semester',
        ondelete='set null',
    )
    currency_id = fields.Many2one(
        comodel_name='res.currency',
        string='Currency',
        required=True,
        default=lambda self: self.env.company.currency_id,
    )

    # --- INVOICE METRICS ---

    total_invoiced = fields.Monetary(
        string='Total Invoiced',
        currency_field='currency_id',
        default=0.0,
        help='Sum of all active invoice totals',
    )
    total_collected = fields.Monetary(
        string='Total Collected',
        currency_field='currency_id',
        default=0.0,
        help='Sum of all confirmed payments',
    )
    total_outstanding = fields.Monetary(
        string='Total Outstanding',
        currency_field='currency_id',
        default=0.0,
        help='Total uncollected fees',
    )
    total_overdue = fields.Monetary(
        string='Total Overdue',
        currency_field='currency_id',
        default=0.0,
        help='Fees from overdue invoices',
    )
    collection_rate = fields.Float(
        string='Collection Rate (%)',
        default=0.0,
        digits=(5, 2),
        help='Percentage of invoiced amount collected',
    )
    invoice_count_total = fields.Integer(
        string='Total Invoices',
        default=0,
    )
    invoice_count_paid = fields.Integer(
        string='Paid Invoices',
        default=0,
    )
    invoice_count_overdue = fields.Integer(
        string='Overdue Invoices',
        default=0,
    )

    # --- SCHOLARSHIP METRICS ---

    total_scholarship_awarded = fields.Monetary(
        string='Scholarship Awarded',
        currency_field='currency_id',
        default=0.0,
    )
    scholarship_beneficiary_count = fields.Integer(
        string='Scholarship Beneficiaries',
        default=0,
    )
    net_revenue = fields.Monetary(
        string='Net Revenue',
        currency_field='currency_id',
        compute='_compute_net_revenue',
        store=True,
    )

    @api.depends('total_collected',
                 'total_scholarship_awarded')
    def _compute_net_revenue(self):
        for rec in self:
            rec.net_revenue = (
                rec.total_collected
                - rec.total_scholarship_awarded
            )

    _sql_constraints = [
        (
            'unique_snapshot_date_company_semester',
            'UNIQUE(snapshot_date, company_id, '
            'semester_id)',
            'A snapshot already exists for this '
            'date, company and semester.',
        ),
    ]

    @api.model
    def generate_daily_snapshot(self):
        """
        Called by scheduled cron action.
        Generates snapshot for all active companies
        using current date. If snapshot already
        exists for today, updates it instead.
        """
        today = date.today()
        companies = self.env['res.company'].search([])

        for company in companies:
            semester = self.env[
                'oacis.semester'
            ].get_current_semester(company.id)

            academic_year = (
                semester.academic_year_id
                if semester else self.env[
                    'oacis.academic.year'
                ].browse()
            )

            # Aggregate directly in SQL: avoids loading whole
            # recordsets into memory and, for legacy payments,
            # includes archived (active=False) rows that the
            # ORM search silently drops.
            semester_clause = (
                ' AND semester_id = %s' if semester else ''
            )
            sem_params = (
                [semester.id] if semester else []
            )

            self.env.cr.execute(
                """
                SELECT
                    COUNT(*),
                    COALESCE(SUM(total_amount), 0),
                    COALESCE(SUM(amount_outstanding), 0),
                    COUNT(CASE WHEN invoice_state = 'paid'
                          THEN 1 END),
                    COUNT(CASE WHEN invoice_state = 'overdue'
                          THEN 1 END),
                    COALESCE(SUM(CASE WHEN invoice_state
                        = 'overdue' THEN amount_outstanding
                        ELSE 0 END), 0)
                FROM oacis_fee_invoice
                WHERE company_id = %s
                  AND invoice_state NOT IN
                      ('draft', 'cancelled')
                """ + semester_clause,
                [company.id] + sem_params,
            )
            (invoice_count_total,
             total_invoiced,
             total_outstanding,
             invoice_count_paid,
             invoice_count_overdue,
             total_overdue) = self.env.cr.fetchone()

            self.env.cr.execute(
                """
                SELECT COALESCE(SUM(collected), 0)
                FROM (
                    SELECT CASE
                        WHEN fi.account_move_id IS NOT NULL
                            THEN GREATEST(
                                fi.total_amount
                                - fi.amount_outstanding, 0)
                        ELSE COALESCE((
                            SELECT SUM(fp.amount)
                            FROM oacis_fee_payment fp
                            WHERE fp.invoice_id = fi.id
                              AND fp.payment_state
                                  = 'confirmed'
                        ), 0)
                    END AS collected
                    FROM oacis_fee_invoice fi
                    WHERE fi.company_id = %s
                      AND fi.invoice_state NOT IN
                          ('draft', 'cancelled')
                """ + (
                    " AND fi.semester_id = %s"
                    if semester else ""
                ) + """
                ) sub
                """,
                [company.id] + sem_params,
            )
            # GL-aware collection total: reconciled residual
            # for GL invoices, confirmed legacy receipts
            # otherwise.
            total_collected = self.env.cr.fetchone()[0]
            collection_rate = (
                round(
                    total_collected / total_invoiced * 100,
                    2,
                )
                if total_invoiced > 0 else 0.0
            )

            self.env.cr.execute(
                """
                SELECT COALESCE(SUM(award_amount), 0),
                       COUNT(DISTINCT student_id)
                FROM oacis_scholarship_award
                WHERE company_id = %s
                  AND award_state = 'disbursed'
                """,
                [company.id],
            )
            total_scholarship, beneficiaries = (
                self.env.cr.fetchone()
            )

            vals = {
                'snapshot_date': today,
                'company_id': company.id,
                'semester_id': (
                    semester.id if semester else False
                ),
                'academic_year_id': (
                    academic_year.id
                    if academic_year else False
                ),
                'currency_id': (
                    company.currency_id.id
                ),
                'total_invoiced': float(total_invoiced),
                'total_collected': float(total_collected),
                'total_outstanding': float(total_outstanding),
                'total_overdue': float(total_overdue),
                'collection_rate': collection_rate,
                'invoice_count_total': invoice_count_total,
                'invoice_count_paid': invoice_count_paid,
                'invoice_count_overdue': (
                    invoice_count_overdue
                ),
                'total_scholarship_awarded': (
                    float(total_scholarship)
                ),
                'scholarship_beneficiary_count': (
                    beneficiaries
                ),
            }

            existing = self.search([
                ('snapshot_date', '=', today),
                ('company_id', '=', company.id),
                ('semester_id', '=',
                 semester.id if semester else False),
            ], limit=1)

            if existing:
                existing.write(vals)
                _logger.info(
                    'Updated finance snapshot for %s.',
                    company.name,
                )
            else:
                self.create(vals)
                _logger.info(
                    'Created finance snapshot for %s.',
                    company.name,
                )
