"""
Oacis Finance Snapshot Model
Daily snapshot of key financial metrics for
trend analysis. Generated by a scheduled action
(cron job) once per day. Stores aggregate totals
so historical trends can be viewed without
computing from transactional data every time.
"""

import logging
from datetime import date

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class OacisFinanceSnapshot(models.Model):
    _name = 'oacis.finance.snapshot'
    _description = 'Daily Financial Snapshot'
    _rec_name = 'display_name'
    _inherit = ['oacis.mixin']

    display_name = fields.Char(
        string='Display Name',
        compute='_compute_display_name',
        store=True,
        depends=['academic_year_id.display_name', 'semester_id.display_name',
                 'snapshot_date'],
    )

    @api.depends('academic_year_id.display_name', 'semester_id.display_name',
                 'snapshot_date')
    def _compute_display_name(self):
        for rec in self:
            context = (
                rec.academic_year_id.display_name
                or rec.semester_id.display_name
                or ''
            )
            if rec.snapshot_date:
                rec.display_name = '%s - %s' % (
                    context,
                    rec.snapshot_date.strftime('%d %b %Y'),
                )
            else:
                rec.display_name = context
    _order = 'snapshot_date desc, company_id'
    _check_company_auto = True

    snapshot_date = fields.Date(
        string='Snapshot Date',
        required=True,
        index=True,
        default=fields.Date.today,
    )
    company_id = fields.Many2one(
        comodel_name='res.company',
        string='Institution',
        required=True,
        default=lambda self: self.env.company,
        ondelete='restrict',
        index=True,
    )
    academic_year_id = fields.Many2one(
        comodel_name='oacis.academic.year',
        string='Academic Year',
        ondelete='set null',
    )
    semester_id = fields.Many2one(
        comodel_name='oacis.semester',
        string='Semester',
        ondelete='set null',
    )
    currency_id = fields.Many2one(
        comodel_name='res.currency',
        string='Currency',
        required=True,
        default=lambda self: self.env.company.currency_id,
    )

    # --- INVOICE METRICS ---

    total_invoiced = fields.Monetary(
        string='Total Invoiced',
        currency_field='currency_id',
        default=0.0,
        help='Sum of all active invoice totals',
    )
    total_collected = fields.Monetary(
        string='Total Collected',
        currency_field='currency_id',
        default=0.0,
        help='Sum of all confirmed payments',
    )
    total_outstanding = fields.Monetary(
        string='Total Outstanding',
        currency_field='currency_id',
        default=0.0,
        help='Total uncollected fees',
    )
    total_overdue = fields.Monetary(
        string='Total Overdue',
        currency_field='currency_id',
        default=0.0,
        help='Fees from overdue invoices',
    )
    collection_rate = fields.Float(
        string='Collection Rate (%)',
        default=0.0,
        digits=(5, 2),
        help='Percentage of invoiced amount collected',
    )
    invoice_count_total = fields.Integer(
        string='Total Invoices',
        default=0,
    )
    invoice_count_paid = fields.Integer(
        string='Paid Invoices',
        default=0,
    )
    invoice_count_overdue = fields.Integer(
        string='Overdue Invoices',
        default=0,
    )

    # --- SCHOLARSHIP METRICS ---

    total_scholarship_awarded = fields.Monetary(
        string='Scholarship Awarded',
        currency_field='currency_id',
        default=0.0,
    )
    scholarship_beneficiary_count = fields.Integer(
        string='Scholarship Beneficiaries',
        default=0,
    )
    net_revenue = fields.Monetary(
        string='Net Revenue',
        currency_field='currency_id',
        compute='_compute_net_revenue',
        store=True,
    )

    @api.depends('total_collected',
                 'total_scholarship_awarded')
    def _compute_net_revenue(self):
        for rec in self:
            rec.net_revenue = (
                rec.total_collected
                - rec.total_scholarship_awarded
            )

    _sql_constraints = [
        (
            'unique_snapshot_date_company_semester',
            'UNIQUE(snapshot_date, company_id, '
            'semester_id)',
            'A snapshot already exists for this '
            'date, company and semester.',
        ),
    ]

    @api.model
    def generate_daily_snapshot(self):
        """
        Called by scheduled cron action.
        Generates snapshot for all active companies
        using current date. If snapshot already
        exists for today, updates it instead.
        """
        today = date.today()
        companies = self.env['res.company'].search([])

        for company in companies:
            semester = self.env[
                'oacis.semester'
            ].get_current_semester(company.id)

            academic_year = (
                semester.academic_year_id
                if semester else self.env[
                    'oacis.academic.year'
                ].browse()
            )

            Invoice = self.env['oacis.fee.invoice']
            Payment = self.env['oacis.fee.payment']
            Award = self.env['oacis.scholarship.award']

            domain_company = [
                ('company_id', '=', company.id),
            ]
            if semester:
                domain_company.append(
                    ('semester_id', '=', semester.id),
                )

            active_invoices = Invoice.search(
                domain_company + [
                    ('invoice_state', 'not in',
                     ['draft', 'cancelled']),
                ],
            )
            total_invoiced = sum(
                i.total_amount for i in active_invoices
            )
            total_outstanding = sum(
                i.amount_outstanding
                for i in active_invoices
            )
            paid_invoices = active_invoices.filtered(
                lambda i: i.invoice_state == 'paid',
            )
            overdue_invoices = active_invoices.filtered(
                lambda i: i.invoice_state == 'overdue',
            )
            total_overdue = sum(
                i.amount_outstanding
                for i in overdue_invoices
            )

            payments = Payment.search([
                ('company_id', '=', company.id),
                ('payment_state', '=', 'confirmed'),
            ])
            total_collected = sum(
                p.amount for p in payments
            )
            collection_rate = (
                round(
                    total_collected / total_invoiced * 100,
                    2,
                )
                if total_invoiced > 0 else 0.0
            )

            awards = Award.search([
                ('company_id', '=', company.id),
                ('award_state', '=', 'disbursed'),
            ])
            total_scholarship = sum(
                a.award_amount for a in awards
            )
            beneficiaries = len(
                set(awards.mapped('student_id').ids),
            )

            vals = {
                'snapshot_date': today,
                'company_id': company.id,
                'semester_id': (
                    semester.id if semester else False
                ),
                'academic_year_id': (
                    academic_year.id
                    if academic_year else False
                ),
                'currency_id': (
                    company.currency_id.id
                ),
                'total_invoiced': total_invoiced,
                'total_collected': total_collected,
                'total_outstanding': total_outstanding,
                'total_overdue': total_overdue,
                'collection_rate': collection_rate,
                'invoice_count_total': len(
                    active_invoices,
                ),
                'invoice_count_paid': len(paid_invoices),
                'invoice_count_overdue': len(
                    overdue_invoices,
                ),
                'total_scholarship_awarded': (
                    total_scholarship
                ),
                'scholarship_beneficiary_count': (
                    beneficiaries
                ),
            }

            existing = self.search([
                ('snapshot_date', '=', today),
                ('company_id', '=', company.id),
                ('semester_id', '=',
                 semester.id if semester else False),
            ], limit=1)

            if existing:
                existing.write(vals)
                _logger.info(
                    'Updated finance snapshot for %s.',
                    company.name,
                )
            else:
                self.create(vals)
                _logger.info(
                    'Created finance snapshot for %s.',
                    company.name,
                )
