from . import (
    unicore_admission_sequence,
    admission_applicant,
    admission_cycle,
    admission_enrollment,
    admission_stage,
    entrance_test,
    offer_letter,
    res_company,
    unicore_course_offering_ext,
    unicore_enrollment,
    unicore_enrollment_log,
    unicore_enrollment_waitlist,
    unicore_student_ext_enrollment,
)
