{
    'name': 'Documents',
    'version': '19.0.1.0.1',
    'category': 'Education',
    'summary': 'Centralised document management for students, faculty and institution',
    'description': """
        Centralised document management for students, faculty and institution
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'unicore_academic',
        'unicore_admission',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_faculty_profile',
        'unicore_security',
        'unicore_student',
    ],
    'data': [
        'security/unicore_documents_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_documents_category_data.xml',
        'views/unicore_document_category_views.xml',
        'views/unicore_document_views.xml',
        'views/document_search_phase1.xml',
        'views/unicore_document_template_views.xml',
        'views/unicore_documents_activity_views.xml',
        'menus/unicore_documents_menus.xml',
        'views/unicore_documents_view_mode_ext.xml',
        'views/unicore_documents_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_documents,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
