{
    'name': 'Attendance Management',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Session attendance tracking, policy enforcement and shortage alerts',
    'description': """
        Session attendance tracking, policy enforcement and shortage alerts
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'oacis_academic',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_faculty_profile',
        'oacis_guardian',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_attendance_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_attendance_policy_data.xml',
        'wizards/oacis_generate_sessions_wizard_views.xml',
        'views/oacis_attendance_policy_views.xml',
        'views/oacis_attendance_session_views.xml',
        'views/oacis_attendance_record_views.xml',
        'views/attendance_search_list_phase1.xml',
        'views/attendance_calendar_phase1.xml',
        'views/oacis_attendance_kanban_views.xml',
        'views/oacis_attendance_calendar_views.xml',
        'views/oacis_attendance_analysis_views.xml',
        'views/oacis_attendance_activity_views.xml',
        'menus/oacis_attendance_menus.xml',
        'views/oacis_attendance_view_mode_ext.xml',
        'views/oacis_attendance_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_attendance,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
