{
    'name': 'Finance Reports',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Financial dashboards, fee analytics and revenue reporting',
    'description': """
        Financial dashboards, fee analytics and revenue reporting
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'unicore_academic',
        'unicore_attendance',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_admission',
        'unicore_exam',
        'unicore_faculty_profile',
        'unicore_fees',
        'unicore_grading',
        'unicore_guardian',
        'unicore_scholarship',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_finance_report_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_finance_report_cron.xml',
        'views/unicore_fee_invoice_report_views.xml',
        'views/unicore_fee_payment_report_views.xml',
        'views/unicore_finance_snapshot_views.xml',
        'views/unicore_finance_kpi_views.xml',
        'views/unicore_finance_dashboard_views.xml',
        'report/unicore_fee_statement_report.xml',
        'report/unicore_fee_statement_template.xml',
        'menus/unicore_finance_report_menus.xml',
        'views/unicore_finance_report_view_mode_ext.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_finance_report,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
