{
    'name': 'Oacis Curriculum',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Program and Curriculum Management for Oacis ERP',
    'description': """
        Program and Curriculum Management for Oacis ERP
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'license': 'OPL-1',
    'depends': [
        'base',
        'oacis_academic',
        'oacis_base',
        'oacis_campus',
        'oacis_faculty_profile',
        'oacis_security',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/oacis_curriculum_record_rules.xml',
        'data/oacis_curriculum_sequence_data.xml',
        'data/oacis_course_category_data.xml',
        'views/oacis_course_views.xml',
        'views/oacis_course_offering_views.xml',
        'views/oacis_curriculum_views.xml',
        'views/oacis_curriculum_line_views.xml',
        'views/oacis_curriculum_kanban_views.xml',
        'views/oacis_curriculum_calendar_views.xml',
        'menus/oacis_curriculum_menus.xml',
        'views/oacis_curriculum_view_mode_ext.xml',
        'views/oacis_curriculum_cleanup.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
