{
    'name': 'Attendance Management',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Session attendance tracking, policy enforcement and shortage alerts',
    'description': """
        Session attendance tracking, policy enforcement and shortage alerts
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'unicore_academic',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_enrollment',
        'unicore_faculty_profile',
        'unicore_guardian',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_attendance_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_attendance_policy_data.xml',
        'wizards/unicore_generate_sessions_wizard_views.xml',
        'views/unicore_attendance_policy_views.xml',
        'views/unicore_attendance_session_views.xml',
        'views/unicore_attendance_record_views.xml',
        'views/attendance_search_list_phase1.xml',
        'views/attendance_calendar_phase1.xml',
        'views/unicore_attendance_kanban_views.xml',
        'views/unicore_attendance_calendar_views.xml',
        'views/unicore_attendance_analysis_views.xml',
        'views/unicore_attendance_activity_views.xml',
        'menus/unicore_attendance_menus.xml',
        'views/unicore_attendance_view_mode_ext.xml',
        'views/unicore_attendance_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_attendance,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
