{
    'name': 'Oacis Students',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Complete student profile and lifecycle management',
    'description': '''
Manages the complete student lifecycle in Oacis ERP.
Covers student profiles, enrollment history,
document management, emergency contacts,
academic history and status transitions.
    ''',
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'oacis_base',
        'oacis_security',
        'oacis_campus',
        'oacis_academic',
        'oacis_academic_generic',
        'oacis_calendar',
    ],
    'data': [
        'security/oacis_student_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_student_sequence_data.xml',
        'data/oacis_bonafide_sequence.xml',
        'wizards/oacis_student_status_wizard_views.xml',
        'wizards/oacis_bonafide_wizard_views.xml',
        'views/oacis_student_views.xml',
        'views/oacis_student_document_views.xml',
        'views/oacis_student_academic_history_views.xml',
        'views/oacis_student_id_card_template.xml',
        'views/oacis_bonafide_template.xml',
        'data/oacis_student_id_card_report.xml',
        'data/oacis_bonafide_report_action.xml',
        'menus/oacis_student_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
