{
    'name': 'Grading & Results',
    'version': '19.0.1.1.0',
    'category': 'Education',
    'summary': 'Marks entry, grade computation, GPA/CGPA and semester results',
    'description': """
        Marks entry, grade computation, GPA/CGPA and semester results
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'oacis_academic',
        'oacis_attendance',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_exam',
        'oacis_faculty_profile',
        'oacis_guardian',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_grading_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_grade_scale_data.xml',
        'data/oacis_transcript_report_action.xml',
        'data/oacis_semester_mark_sheet_report_action.xml',
        'views/oacis_grade_scale_views.xml',
        'views/oacis_grade_entry_views.xml',
        'views/oacis_semester_result_views.xml',
        'views/grading_search_list_phase1.xml',
        'views/oacis_student_result_views.xml',
        'views/oacis_transcript_template.xml',
        'views/oacis_grading_kanban_views.xml',
        'views/oacis_grading_calendar_views.xml',
        'views/oacis_grading_analysis_views.xml',
        'views/oacis_grading_activity_views.xml',
        'views/oacis_semester_mark_sheet_template.xml',
        'menus/oacis_grading_menus.xml',
        'views/oacis_grading_view_mode_ext.xml',
        'views/oacis_grading_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_grading,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
