{
    'name': 'Oacis Faculty & Staff',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Faculty member and administrative staff profile management',
    'description': """
        Faculty member and administrative staff profile management
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'oacis_academic',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_security',
        'oacis_student',
    ],
    'data': [
        'security/oacis_faculty_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_faculty_sequence_data.xml',
        'views/oacis_faculty_qualification_views.xml',
        'views/oacis_faculty_publication_views.xml',
        'views/oacis_faculty_workload_views.xml',
        'views/oacis_staff_member_views.xml',
        'views/oacis_faculty_member_views.xml',
        'views/oacis_faculty_profile_kanban_views.xml',
        'menus/oacis_faculty_profile_menus.xml',
        'views/oacis_faculty_profile_view_mode_ext.xml',
        'views/oacis_faculty_profile_cleanup.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
