{
    'name': 'Admission Management',
    'version': '19.0.1.2.0',
    'category': 'Education',
    'summary': 'Complete admission lifecycle from inquiry to confirmed enrollment',
    'description': """
        Complete admission lifecycle from inquiry to confirmed enrollment
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'oacis_academic',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_security',
        'oacis_student',
        'oacis_curriculum',
        'oacis_faculty_profile',
        'oacis_guardian',
        'oacis_timetable',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/oacis_admission_record_rules.xml',
        'security/oacis_enrollment_record_rules.xml',
        'data/admission_sequence_data.xml',
        'data/oacis_enrollment_sequence_data.xml',
        'data/admission_stage_data.xml',
        'views/admission_cycle_views.xml',
        'views/admission_stage_views.xml',
        'views/admission_applicant_views.xml',
        'views/admission_enrollment_views.xml',
        'views/entrance_test_views.xml',
        'views/offer_letter_views.xml',
        'views/admission_search_list_phase1.xml',
        'views/oacis_admission_kanban_views.xml',
        'views/oacis_admission_calendar_views.xml',
        'views/oacis_admission_activity_views.xml',
        'views/oacis_enrollment_views.xml',
        'views/oacis_enrollment_waitlist_views.xml',
        'views/oacis_enrollment_log_views.xml',
        'views/oacis_course_offering_ext_views.xml',
        'views/oacis_student_ext_enrollment_views.xml',
        'views/oacis_enrollment_kanban_views.xml',
        'views/oacis_enrollment_calendar_views.xml',
        'views/oacis_enrollment_analysis_views.xml',
        'views/oacis_enrollment_activity_views.xml',
        'menus/admission_menus.xml',
        'menus/oacis_enrollment_menus.xml',
        'views/oacis_admission_view_mode_ext.xml',
        'views/oacis_enrollment_view_mode_ext.xml',
        'views/oacis_admission_cleanup.xml',
        'views/oacis_enrollment_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_admission,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
