{
    'name': 'Notifications',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Multi-channel notification engine for email, WhatsApp and in-app alerts',
    'description': """
        Multi-channel notification engine for email, WhatsApp and in-app alerts
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'oacis_academic',
        'oacis_attendance',
        'oacis_base',
        'oacis_calendar',
        'oacis_campus',
        'oacis_curriculum',
        'oacis_admission',
        'oacis_exam',
        'oacis_faculty_profile',
        'oacis_fees',
        'oacis_grading',
        'oacis_guardian',
        'oacis_scholarship',
        'oacis_security',
        'oacis_student',
        'oacis_timetable',
    ],
    'data': [
        'security/oacis_notify_record_rules.xml',
        'security/ir.model.access.csv',
        'data/oacis_notify_config_data.xml',
        'data/oacis_notify_template_data.xml',
        'views/oacis_notification_config_views.xml',
        'views/oacis_notification_template_views.xml',
        'views/oacis_notification_log_views.xml',
        'views/oacis_notify_analysis_views.xml',
        'menus/oacis_notify_menus.xml',
        'views/oacis_notify_view_mode_ext.xml',
        'views/oacis_notify_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'oacis_notify,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
