{
    'name': 'Notifications',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'summary': 'Multi-channel notification engine for email, WhatsApp and in-app alerts',
    'description': """
        Multi-channel notification engine for email, WhatsApp and in-app alerts
    """,
    'author': 'Precisefect Solutions Pvt. Ltd.',
    'website': 'https://precisefect.com',
    'license': 'OPL-1',
    'depends': [
        'mail',
        'unicore_academic',
        'unicore_attendance',
        'unicore_base',
        'unicore_calendar',
        'unicore_campus',
        'unicore_curriculum',
        'unicore_admission',
        'unicore_exam',
        'unicore_faculty_profile',
        'unicore_fees',
        'unicore_grading',
        'unicore_guardian',
        'unicore_scholarship',
        'unicore_security',
        'unicore_student',
        'unicore_timetable',
    ],
    'data': [
        'security/unicore_notify_record_rules.xml',
        'security/ir.model.access.csv',
        'data/unicore_notify_config_data.xml',
        'data/unicore_notify_template_data.xml',
        'views/unicore_notification_config_views.xml',
        'views/unicore_notification_template_views.xml',
        'views/unicore_notification_log_views.xml',
        'views/unicore_notify_analysis_views.xml',
        'menus/unicore_notify_menus.xml',
        'views/unicore_notify_view_mode_ext.xml',
        'views/unicore_notify_cleanup.xml',
    ],
    'images': ['static/description/icon.png'],
    'web_icon': 'unicore_notify,static/description/icon.png',
    'installable': True,
    'application': True,
    'auto_install': False,
}
